const List mylist = [
  {"img": "assets/images/img_1.jpg", "title":"Animals On The Loose","desc":"When wild animals escape from a sanctuary, Bear Grylls — and you — must pursue them and secure their protective habitat.", "url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Animals_On_The_Loose.mp4?alt=media&token=be13a2db-a4d8-4385-91f5-e8341edcdfed",},
  {"img": "assets/images/img_2.jpg","title":"Inside Bill's Brain: Decoding BILL GATES","desc":"Take a trip inside the mind of Bill Gates as the billionaire opens up about those who influenced him and the audacious goals he's still pursuing. ", "url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Inside_Bill's_Brain.mp4?alt=media&token=52161180-a853-4ba1-9208-98d453b088bc",},
  {"img": "assets/images/img_3.jpg","title":"EXODUS: GODS AND KINGS","desc":" The defiant leader Moses rises up against Egyptian Pharaoh Ramses II, setting six hundred thousand slaves on a monumental journey of escape from Egypt and its terrifying cycle of deadly plagues.", "url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/EXODUS_GODS_AND_KINGS.mp4?alt=media&token=ca23e14a-8990-44d3-987d-50c25a0ebdba",},
  {"img": "assets/images/img_4.jpg","title":"Our Planet","desc":"Experience our planet's natural beauty and examine how climate change impacts all living creatures in this ambitious documentary of spectacular scope.", "url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Our_Planet.mp4?alt=media&token=e861e65a-a5a0-4edf-817a-d02d2b9d79d8",},
];

const List popularList = [
  {"img": "assets/images/img_5.jpg" , "title":"AQUAMAN", "desc":"A half-Atlantean, half-human who is reluctant to be king of the undersea nation of Atlantis. He is a member of the Justice League. He possesses superhuman strength, durability, and has the ability to manipulate hydrokinesis, the tides, communicate with sea creatures and swim at supersonic speeds.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/AQUAMAN.mp4?alt=media&token=fe1dabee-d087-4b1c-b4cf-af64fc6c1f8b",},
  {"img": "assets/images/img_6.jpg" , "title":"Age of Samuria: Battle for Japan", "desc":"Considered a fool and unfit to lead, Nobunaga rises to power as the head of the Oda clan, spurring dissent among those in his family vying for control.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Age_of_Samuria.mp4?alt=media&token=10c5b589-7326-4ae6-bba2-76fe6a2d04b5",},
  {"img": "assets/images/img_7.jpg" , "title":"Space Sweepers", "desc":"The film follows a crew of space sweepers who work for UTS collecting space debris and selling it to the company factory. The crew discovers a child robot named Dorothy who contains a weapon of mass destruction created by the terrorist group Black Fox.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Space_Sweepers.mp4?alt=media&token=c1c71c05-5f43-4a6d-bda8-c6e8bd60f4f5",},
  {"img": "assets/images/img_8.jpg" , "title":"Sisyphus", "desc":"An unfathomable incident introduces a genius engineer to dangerous secrets of the world — and to a woman from the future who's come looking for him.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Sisyphus.mp4?alt=media&token=707a92c8-ab78-4a68-b8f2-cee4ed66aa71",},
];

const List trendingList = [
  {"img": "assets/images/img_9.jpg" , "title":"The Vinyang Master: Dream Of Eternity", "desc":"Centuries ago, a malevolent serpent demon was born from the desires of man. Four masters gathered together to trap the snake within the Imperial City, sealed within the body of the Empress, protected by four stone guardians.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/The_Vinyang_Master_Dream_Of_Eternity.mp4?alt=media&token=bce40244-27d8-42af-ba24-e2c9d3f845b4"},
  {"img": "assets/images/img_10.jpg" , "title":"VINCENZO", "desc":"Vincenzo Cassano, Korean-Italian mob lawyer and consigliere of the Cassano crime family, returns to his homeland to search for a place to stash the mob's assets and find further money-laundering business opportunities.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/VINCENZO.mp4?alt=media&token=05ad98e0-1bdc-4a90-8d4c-1f89ba8a1a64"},
  {"img": "assets/images/img_11.jpg" , "title":"Demon Slayer: Kimetsu No Yanba", "desc":"Featuring animation production from revered animation studio Ufotable, the story follows Tanjiro Kamado's journey as a demon slayer after his family is brutally murdered and his sister is turned into a demon.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Demon_Slayer_Kimetsu_No_Yanba.mp4?alt=media&token=c7ec6c25-2e7d-4b37-ada0-f5218079a4a1"},
  {"img": "assets/images/img_12.jpg" ,"title":"Demon Slayer: Kimetsu No Yanba", "desc":"Featuring animation production from revered animation studio Ufotable, the story follows Tanjiro Kamado's journey as a demon slayer after his family is brutally murdered and his sister is turned into a demon.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Demon_Slayer_Kimetsu_No_Yanba_2.mp4?alt=media&token=d1a6599f-8213-4ac6-ba4b-63dd1dee1240"},
];

const List originalList = [
  {"img": "assets/images/img_13.jpg" , "title":"Age of Samuria: Battle for Japan", "desc":"Considered a fool and unfit to lead, Nobunaga rises to power as the head of the Oda clan, spurring dissent among those in his family vying for control.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Age_of_Samuria.mp4?alt=media&token=10c5b589-7326-4ae6-bba2-76fe6a2d04b5"},
  {"img": "assets/images/img_14.jpg" ,"title":"Space Sweepers", "desc":"The film follows a crew of space sweepers who work for UTS collecting space debris and selling it to the company factory. The crew discovers a child robot named Dorothy who contains a weapon of mass destruction created by the terrorist group Black Fox.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Space_Sweepers.mp4?alt=media&token=c1c71c05-5f43-4a6d-bda8-c6e8bd60f4f5"},
  {"img": "assets/images/img_15.jpg" , "title":"The Uncanny Counter", "desc":"The Uncanny Counter follows the story of a young high school student who has been disabled by an accident that took the lives of his parents seven years ago. So Mun (Jo Byeong-kyu) is making a webcomic with his high school chums and going for a bite to eat when he is thrown up into the air.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/The_Uncanny_Counter.mp4?alt=media&token=3fdb4e58-fb2b-4dd2-b90d-9edc909b28b4"},
  {"img": "assets/images/img_20.jpg","title":"Our Planet","desc":"Experience our planet's natural beauty and examine how climate change impacts all living creatures in this ambitious documentary of spectacular scope.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Our_Planet_2.mp4?alt=media&token=db59c797-dd05-4ba5-9149-16c1aaae1551"}
];

const List animeList = [
  {"img": "assets/images/img_16.jpg" , "title":"Black Clover", "desc":"As a lionhearted boy who can't wield magic strives for the title of Wizard King, four banished Wizard Kings of yore return to crush the Clover Kingdom.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Black_Clover.mp4?alt=media&token=a6d7963d-3b89-4bed-9737-4d200dd10ea9"},
  {"img": "assets/images/img_17.jpg" , "title":"Naruto", "desc":"Set before the finale of Naruto, the film focuses on Naruto Uzumaki's ninja team as they go on a mission to stop the moon from falling, and rescue Hanabi Hyuga — Hinata Hyuga's sister — from Toneri Otsutsuki, a man who wishes to marry Hinata and punish mankind for weaponising chakra.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Naruto.mp4?alt=media&token=8723ccfe-8a45-4ec9-99bf-2197940cfc8a"},
  {"img": "assets/images/img_18.jpg" , "title":"Dr. STONE", "desc":" In the year 2019 AD, a mysterious flash suddenly petrifies nearly all human life. The human race frozen in stone for 3,700 years, until in April 5738, a 15-year-old prodigy named Senku Ishigami is suddenly revived to find himself in a world where all traces of human civilization have been eroded by time.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/Dr.STONE.mp4?alt=media&token=8838b6fb-2912-4ba2-9447-8240b1a092cf"},
  {"img": "assets/images/img_19.jpg" , "title":"The Seven Deadly Sins : Imperial Wrath of The Gods", "desc":"Each of the seven high schoolers gets possessed by one of the seven deadly sins -- Wrath, Greed, Gluttony, Lust, Envy, Sloth and Pride. Charlie's evil spirit pushes each high schooler to the brink of their sanity in hopes to completely own their soul.","url":"https://firebasestorage.googleapis.com/v0/b/netflix-clone-dbae7.appspot.com/o/The_Seven_Deadly_Sins.mp4?alt=media&token=5abcc2cb-7b91-4209-a158-c01536ab07f7"},
];
